# Generated by Django 6.0.2 on 2026-02-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cca3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name_common', models.CharField(max_length=255)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('area', models.FloatField()),
                ('flag_url', models.URLField(max_length=500)),
            ],
        ),
    ]
