# Generated by Django 6.0.2 on 2026-02-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_currency_code_country_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(),
        ),
    ]
